import sbtghactions.WorkflowStep.{Run, Sbt, Use}
import sbtghactions.{JavaSpec, UseRef, WorkflowJob, WorkflowStep}

// Generated by `sbt githubWorkflowGenerate` (sbt-github-actions).
// GHCR publish stays in `.github/workflows/container.yml`.
// Play 3.0.x tracks sbt 1.x; stay on latest 1.x (not sbt 2) until Play ships stable sbt 2 support.

ThisBuild / scalaVersion := "2.13.18"
ThisBuild / crossScalaVersions := Seq("2.13.18")
ThisBuild / githubWorkflowScalaVersions := Seq("2.13.18")
ThisBuild / githubWorkflowOSes := Seq("ubuntu-26.04")
ThisBuild / githubWorkflowJavaVersions := Seq(JavaSpec.temurin("25"))
ThisBuild / githubWorkflowPublishTargetBranches := Seq()
ThisBuild / githubWorkflowArtifactUpload := false
ThisBuild / githubWorkflowIncludeClean := false
ThisBuild / githubWorkflowTargetBranches := Seq("main", "master")
ThisBuild / githubWorkflowTargetTags := Seq("v*")
ThisBuild / githubWorkflowBuildSbtStepPreamble := Nil

ThisBuild / githubWorkflowBuildPreamble := Seq(
  Use(
    UseRef.Public("actions", "setup-node", "v7"),
    name = Some("Setup Node"),
    params = Map(
      "node-version" -> "24",
      "cache" -> "npm",
      "cache-dependency-path" -> "package-lock.json"
    )
  ),
  Run(
    List(
      "npm ci --ignore-scripts",
      "node_modules/.bin/eslint -c conf/eslint.json 'src/app/**/*.js'",
      "node -e \"require('grunt').tasks(['assets'])\"",
      "npm test -- --singleRunTests"
    ),
    name = Some("Angular assets")
  )
)

ThisBuild / githubWorkflowBuild := Seq(
  Sbt(List("test"), name = Some("Backend test"))
)

ThisBuild / githubWorkflowAddedJobs += WorkflowJob(
  id = "container",
  name = "Container smoke",
  oses = List("ubuntu-26.04"),
  scalas = List("2.13.18"),
  javas = List(JavaSpec.temurin("25")),
  steps = List(
    WorkflowStep.Checkout,
    Run(
      List(
        "set -euo pipefail",
        "podman --version",
        "buildah --version",
        "podman build -t localhost/cerebro-opensearch:ci -f Containerfile .",
        "CEREBRO_IMAGE=localhost/cerebro-opensearch:ci CEREBRO_URL=http://127.0.0.1:9000 bash scripts/smoke-opensearch-matrix.sh"
      ),
      name = Some("Build and smoke image with Podman (OpenSearch latest + 2.x)")
    )
  )
)
